# Copyright 2025 SpinQ Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x81\x01\n\x0b\x42\x61seMessage\x12\x1b\n\x08metadata\x18\x01 \x01(\x0b\x32\t.Metadata\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\x12 \n\nchart_data\x18! \x01(\x0b\x32\n.ChartDataH\x00\x12\x13\n\tjson_data\x18, \x01(\tH\x00\x42\x0e\n\x0cmessage_type\"W\n\x08Metadata\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x61\x63\x63ount\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t\"\xb6\x01\n\tChartData\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x12\n\nchart_name\x18\x03 \x01(\t\x12\x11\n\x04path\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05qubit\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04step\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x1f\n\x06points\x18\x07 \x03(\x0b\x32\x0f.DataPointProtoB\x07\n\x05_pathB\x08\n\x06_qubitB\x07\n\x05_step\"&\n\x0e\x44\x61taPointProto\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASEMESSAGE']._serialized_start=18
  _globals['_BASEMESSAGE']._serialized_end=147
  _globals['_METADATA']._serialized_start=149
  _globals['_METADATA']._serialized_end=236
  _globals['_CHARTDATA']._serialized_start=239
  _globals['_CHARTDATA']._serialized_end=421
  _globals['_DATAPOINTPROTO']._serialized_start=423
  _globals['_DATAPOINTPROTO']._serialized_end=461
# @@protoc_insertion_point(module_scope)
