syntax = "proto3";

message BaseMessage {
  Metadata metadata = 1;
  string msg_id = 2; // 消息类型：用来区分不同的业务操作

  // 使用oneof，表示使用其中一种格式进行传输
  oneof message_type {
    ChartData chart_data = 33; // 谱线数据格式
    string json_data = 44; // json字符串格式
  } 
}

/**
* 每条报文都需要的报文数据
*/
message Metadata {
  int64 sequence_id = 1; // 主动类型的消息需要创建唯一的消息ID，如果是应答消息，必须把请求消息数据包中的这个字段返回，以形成闭环
  int64 timestamp = 2; // 消息的时间戳
  string account = 4; // 发送消息的用户名称
  string session_id = 5;// 登录得到的会话id
}

/**
* 谱线数据
*/
message ChartData {
  string task_id = 1; // 所属任务id
  string group = 2; // 所属实验
  string chart_name = 3; // 图表名称
  optional string path=4; // 图表通道
  optional string qubit =5; // 图表比特？三比特有，后续扩展
  optional string step = 6; // 观测步骤
  repeated DataPointProto points = 7;
}

message DataPointProto {
  float x = 1;
  float y = 2;
}